config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "imeis#index"
  resources :imeis
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/imei.rb
class Imei < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imeis_controller.rb
class ImeisController < ApplicationController
  def index
    @imeis = Imei.all
  end

  def show
    @imei = Imei.find(params[:id])
  end

  def new
    @imei = Imei.new
  end

  def create
    @imei = Imei.new(imei_params)
    result = Classify::Classify.new(params[:imei][:imei], params[:imei][:month_year])
    @imei.result = result.fraudulent?
    if @imei.save
      redirect_to @imei
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def imei_params
    params.require(:imei).permit(:imei, :month_year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imeis_helper.rb
module ImeisHelper
end

app/views/imeis/_fraud.html.erb
<h2>Fraud  Data</h2>

app/views/imeis/index.html.erb
<h1>Data</h1>
<%= link_to "New Data", new_imei_path %>

<ul>
  <% @imeis.each do |imei| %>
    <li>
        <%= link_to imei.imei, imei %>
    </li>
  <% end %>
</ul>

app/views/imeis/new.html.erb
<h1>New Data</h1>

<%= form_with model: @imei do |form| %>
  <div>
    <%= form.label :imei %><br>
    <%= form.text_field :imei %>
  </div>

  <div>
    <%= form.label :month_year %><br>
    <%= form.text_field :month_year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/imeis/show.html.erb
<h2>Imei: <%= @imei.imei %></h2>
<h2>Month Year<%= @imei.month_year %></h2>
<h2>Result: <%= @imei.result %></h2>

<% if @imei.result === "Bad" %>
    <%= render 'fraud' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prototype</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>